version: '2'
services:
  demo:
    image: node:9.3-alpine
    container_name: demo
    command: npm run dev
    working_dir: /app
    volumes:
      - ./:/app:cached
    environment:
      - NODE_ENV=development
      - PORT=8000
    ports:
      - '1025:8000'
